### ISSUE TITLE
Compilation error when postrgex not installed

### ISSUE THREAD

**Issue by asmodehn** [tbug/elixir_interval#19]
Hi, I recently attempted to add `interval` to my project.
However it didn't compile :

 ```
 ± mix deps.compile interval
==> interval
Compiling 10 files (.ex)

== Compilation error in file lib/interval/integer.ex ==
** (CompileError) lib/interval/support/ecto.ex:22: Postgrex.Range.__struct__/0 is undefined, cannot expand struct Postgrex.Range. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code

could not compile dependency :interval, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile interval", update it with "mix deps.update interval" or clean it with "mix deps.clean interval"
```

I am guessing this is because I do not have postgrex as a dependency:
```
± mix deps.tree | grep postgrex

``` 
I also noticed postrgex is not listed in `interval` dependencies ?
```
==> xest_clock
xest_clock
└── interval ~> 0.3.1 (Hex package)
```
Also https://hex.pm/packages/interval says `Dependencies(0)`
Not sure what would be the preferred way to fix this... Let me know and I can have a go at it ;-)

Cheers, and big thanks for the useful work !

**Comment by tbug** [comment]
Yes, sorry, I accidentally broke that :)
I have the same problem in one of my own projects that doesn't use postgres.
I'll fix that asap.

**Comment by asmodehn** [comment]
Oh, if you re aware of it, no worries then ;-) Your projects are much cleaner than mine...
Anyway it s pushing me to understand better how module compilation and dependencies work...

Thanks again !

**Comment by asmodehn** [comment]
Thanks !
I tested 0.3.3 which now compile as expected for my project:
```
==> interval
Compiling 9 files (.ex)
Generated interval app
```
